
package com.levymoreira.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebServiceInterface", targetNamespace = "http://ws.levymoreira.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebServiceInterface {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.levymoreira.ws.Produto
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws.levymoreira.com/WebServiceInterface/printMessageRequest", output = "http://ws.levymoreira.com/WebServiceInterface/printMessageResponse")
    public Produto printMessage(
        @WebParam(name = "arg0", partName = "arg0")
        Produto arg0);

}
